// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tprfvkfvarhskprpdlwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwcmZ2a2Z2YXJoc2twcnBkbHd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMTk0MzIsImV4cCI6MjA2Njg5NTQzMn0.RWPxKp_mV-a0C7zAcTMnJi5kL74NRqUisZqZuvjEA_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});